### ISSUE TITLE
Usage of os.walk()

### ISSUE THREAD

**Issue by ykabbara** [elmoallistair/Google-IT-Automation-with-Python-Professional-Certificate#5]
Hi Elmo, 

Thank you for sharing this content, I have a question, in the c4_troubleshooting-debugging-techniques/2_slowness/graded-assessment/dailysync.py as per the hint below they gave a hint to use os.walk() which gave me a lot of headache especially dealing with file names and so on, and I can find that you didn't use it as well, any reason why and how the code would change in case you use it?

Hint: os.walk() generates the file names in a directory tree by walking the tree either top-down or bottom-up. This is used to traverse the file system in Python. 

Best,
Yusuf

**Comment by elmoallistair** [comment]
Hi Yusuf, 

Unfortunately I can't remember what this assessment was about

But as I recall, our job is to implement multiprocessing to sync data from folder `/data/prod` to `/data/prod_backup` (and they already provide `src` and` dest`).
So our job is to implement it directly using `subprocess.call(["rsync ","-arq", src, dest])`

&nbsp;

...maybe they want us to get the folders by traverse the `src` folder with `os.walk()` joining the absolute path to the folder.

So i've tried this (just for reference):

Structure:

```
data
├── prod
│   ├── folder1
│   └── folder2
└── prod_backup
```

Code:

```
folders = []
src = "/data/prod/"
for root, _dir, files in os.walk(src):
    for name in _dir:
        folders.append(os.path.join(root, name))
```

Result:

```
>>> folders
['/data/prod/folder2', '/data/prod/folder1']
```

So you can apply pool per folder instead of `src`:

```
for folder in folders:
    pool.apply(subprocess.call, args=(["rsync", "-arq", folder, dest],))
```

&nbsp;

However I can't confirm this because I can't access the content :)

**Comment by ykabbara** [comment]
Hi Elmo, first of all I really appreciate quick response.

Yeah I think this is exactly what is wanted, now I tried the same but it's giving all subfolders, not a big deal but I couldn't change the behavior :)

Best regards and thank you :)
